### ISSUE TITLE
Path must be string

### ISSUE THREAD

**Issue by hbarve1** [tapio/live-server#189]
Using live-server from Node with the configuration you have provided
```
const liveServer = require("live-server");

const params = {
  port: 4000, // Set the server port. Defaults to 8080.
  host: "localhost", // Set the address to bind to. Defaults to 0.0.0.0 or process.env.IP.
  // path: "/",
  root: "/public", // Set root directory that's being served. Defaults to cwd.
  open: false, // When false, it won't load your browser by default.
  ignore: 'scss, node_modules', // comma-separated string for paths to ignore
  file: "index.html", // When set, serve this file for every 404 (useful for single-page applications)
  wait: 100, // Waits for all changes, before reloading. Defaults to 0 sec.
  mount: [['./node_modules']], // Mount a directory to a route.
  logLevel: 2, // 0 = errors only, 1 = some, 2 = lots
  middleware: [function(req, res, next) { next(); }] // Takes an array of Connect-compatible middleware that are injected into the server middleware stack
};

liveServer.start(params);

```
It is throwing this error.

Can you please help me out??

```
 0 info it worked if it ends with ok
1 verbose cli [ '/home/himank/.nvm/versions/node/v6.9.5/bin/node',
1 verbose cli   '/home/himank/.nvm/versions/node/v6.9.5/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.1.2
3 info using node@v6.9.5
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle mayash-template@1.0.0~predev: mayash-template@1.0.0
6 silly lifecycle mayash-template@1.0.0~predev: no script for predev, continuing
7 info lifecycle mayash-template@1.0.0~dev: mayash-template@1.0.0
8 verbose lifecycle mayash-template@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle mayash-template@1.0.0~dev: PATH: /home/himank/.nvm/versions/node/v6.9.5/lib/node_modules/npm/bin/node-gyp-bin:/home/himank/NodeProjects/mayash-template/node_modules/.bin:/home/himank/.nvm/versions/node/v6.9.5/bin:/home/himank/mongodb/bin:/usr/local/heroku/bin:/home/himank/bin:/home/himank/mongodb/bin:/usr/local/heroku/bin:/home/himank/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/himank/Android/Sdk/platform-tools:/home/himank/Android/Sdk/platform-tools
10 verbose lifecycle mayash-template@1.0.0~dev: CWD: /home/himank/NodeProjects/mayash-template
11 silly lifecycle mayash-template@1.0.0~dev: Args: [ '-c', 'babel-node live-server.js' ]
12 silly lifecycle mayash-template@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle mayash-template@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: mayash-template@1.0.0 dev: `babel-node live-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/himank/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/himank/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid mayash-template@1.0.0
16 verbose cwd /home/himank/NodeProjects/mayash-template
17 error Linux 4.4.0-64-generic
18 error argv "/home/himank/.nvm/versions/node/v6.9.5/bin/node" "/home/himank/.nvm/versions/node/v6.9.5/bin/npm" "run" "dev"
19 error node v6.9.5
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error mayash-template@1.0.0 dev: `babel-node live-server.js`
22 error Exit status 1
23 error Failed at the mayash-template@1.0.0 dev script 'babel-node live-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mayash-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node live-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mayash-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mayash-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by pavel** [comment]
This:
```
mount: [['./node_modules']], // Mount a directory to a route.
```
is wrong. Mount entry is a 2 items array: ['path', 'file system path']. I assume you wanted something like this:
```
mount: [['/node_modules', './node_modules']], // Mount a directory to a route.
```
See usage in [README.md](https://github.com/tapio/live-server#usage-from-node).
