### ISSUE TITLE
live-server --browser=chrome throwing error

### ISSUE THREAD

**Issue by rajakvk** [tapio/live-server#195]
live-server --browser=chrome throwing following error
/usr/local/lib/node_modules/live-server/live-server.js:73
	process.chdir(process.argv[2]);
	        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/live-server/live-server.js:73:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3

Am on Mac 10.11.6 El Capiton

Not sure, this is configuration issue or live-server issue.

**Comment by doronbehar** [comment]
I think you should use `--browser=google-chrome`. I'm not sure about Mac OS, but on Linux, the executable that can be found on `$PATH` when installing Google Chrome is usually `google-chrome`.

**Comment by jrmclaren** [comment]
I ran the command using `--browser='Google Chrome'`. This config worked work me on Mac OS 10.13.2 High Sierra.

**Comment by agarwalkoustubh38** [comment]
> I think you should use `--browser=google-chrome`. I'm not sure about Mac OS, but on Linux, the executable that can be found on `$PATH` when installing Google Chrome is usually `google-chrome`.

thanks it worked  for me
