### ISSUE TITLE
1.2.0 issue with 'send' module

### ISSUE THREAD

**Issue by dolanmiu** [tapio/live-server#202]
My command is: 

```
live-server --watch=dist
```

But I get error:

```
Error: Cannot find module 'send'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dolan/flappy-bird-client/node_modules/live-server/index.js:10:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Switching back to `1.1.0`

**Comment by vogloblinsky** [comment]
Any news on this @tapio ?

**Comment by vogloblinsky** [comment]
Any news on this @tapio ?
