### ISSUE TITLE
Cannot use it with node 6

### ISSUE THREAD

**Issue by pm-radu** [tapio/live-server#305]
## Issue description
Cannot run `live-server` on node 6 anymore because of `opn` dependency.

## Software details
`live-server` has a dependency to `opn` in `package.json`:
`"opn": "latest"`

Few days ago, `opn` introduced new code which uses `async/await`. This feature is not supported in `node 6` which I am currently using. If I try to run this simple example:
```
var liveServer = require("live-server");
liveServer.start({});
```
I get this error:
```
C:\code\temp\live\node_modules\opn\index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\temp\live\node_modules\live-server\index.js:11:9)
```

* OS: Windows 10
* Node.js version: 6
* `live-server` version: 1.2.1

My `package.json`:
```
{
  "name": "live",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "live-server": "^1.2.1"
  }
}
```

**Comment by pm-radu** [comment]
Is this repo abandonded?

**Comment by jaredellison** [comment]
Nice write up @pm-radu, also seeing this issue here. 

It appears the two options for resolving it are to modify the project's `package.json` on [line 48](https://github.com/tapio/live-server/blob/01cd7f970439d42537bbe13b4885befb816a0446/package.json#L48) to specify a version of Node.js greater than 7.6 when support was added for `async/await`. Additionally the dependency `opn` is now called [`open`](https://www.npmjs.com/package/open) and should be updated.

Alternately if maintaining support for the oldest versions of Node is a priority, [line 24](https://github.com/tapio/live-server/blob/01cd7f970439d42537bbe13b4885befb816a0446/package.json#L24) could be modified to specify the last `opn` version without `async/await` which is 5.4.0.

**Comment by pm-radu** [comment]
Thanks @jaredellison 
Does it mean I have to maintain a fork of `live-server` only for that `opn` version?

**Comment by jaredellison** [comment]
@pm-radu that's definitely one option.

Looking towards long term viability, have you considered moving to a newer version of Node.js instead? Maybe the latest LTS version, `10.15.3`? It's likely you'll want to use other libraries that make use of newer language features and moving forward with a platform can be helpful for general compatibility and security.

If you do need to stick with Node 6 for your project perhaps the [Node version manager](https://github.com/nvm-sh/nvm) would be helpful?
