### ISSUE TITLE
live server neither opening from cmd nor from vs code go live button

### ISSUE THREAD

**Issue by jagga420** [tapio/live-server#309]
live server command giving error from cmd and getting this error after running the command: 
`PS E:\JCM\Projects\Travel Companion> live-server
Serving "E:\JCM\Projects\Travel Companion" at http://127.0.0.1:8080
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

* Command line used for launching `live-server`: live-server
* OS: Windows 10
* Browser (if browser related): chrome
* Node.js version: 10.15.3
* `live-server` version: 1.2.1

**Comment by krishnaUIDev** [comment]
did you solve this issue? I got this issue just now.

**Comment by akschavan100** [comment]
hey any one can solve this issue? i had this same issue.

**Comment by iyasmavoor** [comment]
thanks me  also suffering same
