### ISSUE TITLE
Can't start Chromium in debugging mode with live-server command line

### ISSUE THREAD

**Issue by David-Else** [tapio/live-server#311]
## Issue description

I can't seem to start chromium in debugging mode with live-server. I am assuming the command needs `''` or `""` around `chromium-browser --remote-debugging-port=9222`, but neither works. I can't find any option to pass parameters to the browser.

I can start chromium in debugging mode and then use `live-server` and it opens another tab and all is well... but this seems like a hack.

I get:

```
npx live-server --browser=/usr/bin/'chromium-browser --remote-debugging-port=9222'

Serving "/location" at http://127.0.0.1:8080
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/chromium-browser --remote-debugging-port=9222 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:58:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:17:11
```

## Software details

* Command line used for launching `live-server`: npx live-server --browser=/usr/bin/'chromium-browser --remote-debugging-port=9222'

* OS: Fedora 29 
* Browser (if browser related): Chromium
* Node.js version: 12
* `live-server` version: 1.21

**Comment by David-Else** [comment]
Happy Christmas, closing due to being nearly 2 years stale.
